# /////////////////////////////////////////////////////////////
# /                                                           /
# /                      Logger Plugin                        /
# /                                                           /
# /                    [ Proxy Version ]                      /
# /                                                           /
# /////////////////////////////////////////////////////////////
#
# Thank you for using Logger Plugin! If you are experiencing any issues
# or have any suggestions / features you want to be implemented into the plugin
# feel free to join the support Discord Server!
#
# Spigot: Prism3
# Discord: Prism3#5787 | ID: 403667971089760257
# Discord Server: https://discord.gg/MfR5mcpVfX

# Server Name
Server-Name: "Server_Name"

# How many Days for the logs to be deleted
# Set it to -1 to cancel the Deletion
File-Deletion: 7

# Log to Files
Log-to-Files: true

# This will log players with "loggerbungee.staff.log" permission node in their own folder / file
Staff:
  Enabled: false

# Logging features
Log:
  Player-Chat: true
  Player-Login: true
  Player-Leave: true
  Server-Reload: true
  Server-Start: true
  Server-Stop: true

# Disable to hide Player's IPs
Player-Login:
  Player-IP: true

# MySQL Feature
# Data-Deletion Value in Days, Set it -1 to cancel
MySQL:
  Enable: false
  Host: localhost
  Port: 3306
  Username: username
  Password: PassworD
  Database: database
  Data-Deletion: 7