# /////////////////////////////////////////////////////////////
# /                                                           /
# /                      Logger Plugin                        /
# /                                                           /
# /                  [ BungeeCord Version ]                   /
# /                                                           /
# /////////////////////////////////////////////////////////////
#
# Thank you for using Logger Plugin! If you are experiencing any issues
# or have any suggestions / features you want to be implemented into the plugin
# feel free to join the support Discord Server!
#
# Spigot: Prism3
# Discord: Prism3#5787 | Prism3#0003 | ID: 403667971089760257
# Discord Server: https://discord.gg/MfR5mcpVfX
#
# Config 1.7.1

# Server Name
Server-Name: "Server_Name"

# How many Days for the logs to be deleted
# Set it to -1 to cancel the Deletion
File-Deletion: 7

# Log to Files
Log-to-Files: true

# This will log players with "loggerproxy.staff.log" permission node in their own folder / file
Staff:
  Enabled: false

# Logging features
Log-Player:
  Chat: true
  Command: true
  Login: true
  Leave: true

# Server Side Part
Log-Server:
  Reload: true
  Start: true
  Stop: true

# Disable to hide Player's IPs
Player-Login:
  Player-IP: true

Player-Commands:
  BlackListed-Commands:
    - /login
    - /register
    - /msg

# MySQL Feature
# Data-Deletion Value in Days, Set it -1 to cancel
MySQL:
  Enable: false
  Host: localhost
  Port: 3306
  Username: username
  Password: PassworD
  Database: database
  Data-Deletion: 7

# SQLite Feature
# Data-Deletion Value in Days, Set it -1 to cancel
SQLite:
  Enable: false
  Data-Deletion: 7